version: "1"
services:
  web:
    container_name: my-app
    restart: always
    depends_on:
      - redis
    build: . 
    ports: 
    - "3001:3001"
    links: 
      - redis
  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"